//Teste de Requisições REST - Prestadores
//@baseURL = https://projetoalexandria.herokuapp.com/api
@baseURL = http://localhost:4000/api
@id = 629e361678caf871a5151b0f
@nome =
@razao = capura
###
// GET - Lista todos os livros
GET {{baseURL}}/livros
Content-Type: application/json

###
// GET - Lista apenas um livro pelo id
GET {{baseURL}}/livros/id/{{id}}
Content-Type: application/json

###
// POST - Inclui um novo livro
POST {{baseURL}}/livros
Content-Type: application/json

{
   "nome": "Duna",
   "autor": "Frank Herbet",
   "lançamento": "1965",
   "gênero": "Ficção Científica",
   "paginas": "1000"
}

### 
// DELETE - Apaga um livro através do id informado
DELETE {{baseURL}}/livros/{{id}}
Content-Type: application/json

### 
// DELETE - Apaga um livro através do nome informado
DELETE {{baseURL}}/livros/{{nome}}
Content-Type: application/json

###
// PUT - Altera um livro pelo ID
PUT {{baseURL}}/livros
Content-Type: application/json

{
   "_id": "629e361678caf871a5151b0f",
   "nome": "Duna",
   "autor": "Frank Herbet",
   "lançamento": "1965",
   "gênero": "Ficção Científica",
   "paginas": "1000"
}