//Teste de Requisições REST - Prestadores
//@baseURL = https://projetoalexandria.herokuapp.com/api
@baseURL = http://localhost:4000/api
@id = 629d9781b2f40e9bde18b754
@razao = capura
###
// GET - Lista todos os livros
GET {{baseURL}}/livros
Content-Type: application/json

###
// GET - Lista apenas um livro pelo id
GET {{baseURL}}/livros/id/{{id}}
Content-Type: application/json

###
// POST - Inclui um novo livro
POST {{baseURL}}/livros
Content-Type: application/json

{
   "nome": "Duna",
   "autor": "José de Alencar",
   "publicação": "1856",
   "gênero": "Romance",
   "N° de pagnias": "1000"
}

### 
// DELETE - Apaga um livro através do id informado
DELETE {{baseURL}}/livros/{{id}}
Content-Type: application/json

###
// PUT - Altera um livro pelo ID
PUT {{baseURL}}/livros
Content-Type: application/json

{
   "_id": "6267f34532ae23b306a82e20",
   "nome": "Duna",
   "autor": "José de Alencar",
   "publicação": "1856",
   "gênero": "Romance",
   "N° de pagnias": "1000"
}